[2024-11-27T02:17:11.624+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-27T02:17:11.645+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: amazon_recommendation_pipeline.transform_data scheduled__2024-11-26T00:00:00+00:00 [queued]>
[2024-11-27T02:17:11.651+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: amazon_recommendation_pipeline.transform_data scheduled__2024-11-26T00:00:00+00:00 [queued]>
[2024-11-27T02:17:11.652+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 4
[2024-11-27T02:17:11.661+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data> on 2024-11-26 00:00:00+00:00
[2024-11-27T02:17:11.669+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'amazon_recommendation_pipeline', 'transform_data', 'scheduled__2024-11-26T00:00:00+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/amazon_recommendation_dag.py', '--cfg-path', '/tmp/tmpd66kvkoc']
[2024-11-27T02:17:11.670+0000] {standard_task_runner.py:91} INFO - Job 69: Subtask transform_data
[2024-11-27T02:17:11.673+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=8274) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-27T02:17:11.673+0000] {standard_task_runner.py:63} INFO - Started process 8276 to run task
[2024-11-27T02:17:11.711+0000] {task_command.py:426} INFO - Running <TaskInstance: amazon_recommendation_pipeline.transform_data scheduled__2024-11-26T00:00:00+00:00 [running]> on host 0db19616cf8d
[2024-11-27T02:17:11.777+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='amazon_recommendation_pipeline' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-26T00:00:00+00:00'
[2024-11-27T02:17:11.779+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-27T02:17:11.780+0000] {spark_transform_task.py:66} ERROR - An error occurred: [Errno 13] Permission denied: '/app'
[2024-11-27T02:17:11.780+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-27T02:17:11.781+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/spark_transform_task.py", line 26, in transform_data
    os.makedirs(PROCESSED_DATA_PATH, exist_ok=True)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/app'
[2024-11-27T02:17:11.789+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=amazon_recommendation_pipeline, task_id=transform_data, run_id=scheduled__2024-11-26T00:00:00+00:00, execution_date=20241126T000000, start_date=20241127T021711, end_date=20241127T021711
[2024-11-27T02:17:11.797+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 69 for task transform_data ([Errno 13] Permission denied: '/app'; 8276)
[2024-11-27T02:17:11.807+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-27T02:17:11.822+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-27T02:17:11.825+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
