[2024-11-26T08:52:34.541+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-26T08:52:34.564+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: amazon_pipeline.extract_data manual__2024-11-26T08:52:30.843794+00:00 [queued]>
[2024-11-26T08:52:34.570+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: amazon_pipeline.extract_data manual__2024-11-26T08:52:30.843794+00:00 [queued]>
[2024-11-26T08:52:34.571+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-11-26T08:52:34.580+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data> on 2024-11-26 08:52:30.843794+00:00
[2024-11-26T08:52:34.590+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'amazon_pipeline', 'extract_data', 'manual__2024-11-26T08:52:30.843794+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/amazon_pipeline_dag.py', '--cfg-path', '/tmp/tmp6k4i8ws9']
[2024-11-26T08:52:34.591+0000] {standard_task_runner.py:91} INFO - Job 16: Subtask extract_data
[2024-11-26T08:52:34.594+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2698) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-26T08:52:34.594+0000] {standard_task_runner.py:63} INFO - Started process 2711 to run task
[2024-11-26T08:52:34.625+0000] {task_command.py:426} INFO - Running <TaskInstance: amazon_pipeline.extract_data manual__2024-11-26T08:52:30.843794+00:00 [running]> on host ca7d491041e1
[2024-11-26T08:52:34.679+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='amazon_pipeline' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-26T08:52:30.843794+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-26T08:52:30.843794+00:00'
[2024-11-26T08:52:34.680+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-26T08:52:35.804+0000] {logging_mixin.py:188} INFO - <Response [503]>
[2024-11-26T08:52:35.805+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-26T08:52:35.805+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/scraper_task.py", line 16, in scrape_amazon
    raise Exception(f"Failed to fetch data. Status code: {response.status_code}")
Exception: Failed to fetch data. Status code: 503
[2024-11-26T08:52:35.814+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=amazon_pipeline, task_id=extract_data, run_id=manual__2024-11-26T08:52:30.843794+00:00, execution_date=20241126T085230, start_date=20241126T085234, end_date=20241126T085235
[2024-11-26T08:52:35.821+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 16 for task extract_data (Failed to fetch data. Status code: 503; 2711)
[2024-11-26T08:52:35.851+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-26T08:52:35.866+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-26T08:52:35.867+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
