[2024-11-26T09:14:32.227+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-26T09:14:32.247+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: amazon_pipeline.process_and_load_data scheduled__2024-11-25T00:00:00+00:00 [queued]>
[2024-11-26T09:14:32.253+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: amazon_pipeline.process_and_load_data scheduled__2024-11-25T00:00:00+00:00 [queued]>
[2024-11-26T09:14:32.254+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 4
[2024-11-26T09:14:32.263+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): process_and_load_data> on 2024-11-25 00:00:00+00:00
[2024-11-26T09:14:32.273+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'amazon_pipeline', 'process_and_load_data', 'scheduled__2024-11-25T00:00:00+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/amazon_pipeline_dag.py', '--cfg-path', '/tmp/tmpguso48n9']
[2024-11-26T09:14:32.274+0000] {standard_task_runner.py:91} INFO - Job 45: Subtask process_and_load_data
[2024-11-26T09:14:32.276+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=6119) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-26T09:14:32.277+0000] {standard_task_runner.py:63} INFO - Started process 6146 to run task
[2024-11-26T09:14:32.309+0000] {task_command.py:426} INFO - Running <TaskInstance: amazon_pipeline.process_and_load_data scheduled__2024-11-25T00:00:00+00:00 [running]> on host d62e07581dba
[2024-11-26T09:14:32.362+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='amazon_pipeline' AIRFLOW_CTX_TASK_ID='process_and_load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T00:00:00+00:00'
[2024-11-26T09:14:32.363+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-26T09:14:32.479+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-26T09:14:32.480+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/spark_milvus_task.py", line 16, in process_and_insert_data
    spark = SparkSession.builder.appName("AmazonDataPipeline").getOrCreate()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-11-26T09:14:32.488+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=amazon_pipeline, task_id=process_and_load_data, run_id=scheduled__2024-11-25T00:00:00+00:00, execution_date=20241125T000000, start_date=20241126T091432, end_date=20241126T091432
[2024-11-26T09:14:32.497+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 45 for task process_and_load_data ([JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.; 6146)
[2024-11-26T09:14:32.530+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-26T09:14:32.541+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-26T09:14:32.543+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
